version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 01141721211Kk
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://your_user:your_password@db/your_db
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://your_user:your_password@db/your_db
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data: {}
